### ISSUE TITLE
Pushing to a private registry

### ISSUE THREAD

**Issue by bracki** [harbur/captain#27]
How do I push my images to a private registry when calling `captain push`?
Can I configure this?

**Comment by spiddy** [comment]
Hi,

You should login using `docker login` as normal. If the logged in user has
write access to the namespace resolved by captain push it should work as
expected.

The namespace is resolved by captain through either captain.yml file or
dynamically using <machine_username>/<project_directory>

It will push three tags:
- latest
- branchname
- tagname(s) (if they are any)

What's your current use case?

**Comment by bracki** [comment]
Thanks, I figured that out 20 minutes later ;).
