### ISSUE TITLE
captain push should include also the git tag version

### ISSUE THREAD

**Issue by ludovicc** [harbur/captain#32]
Currently it pushes the image with the tags `:latest`, `:master` and `:<branch>`, can you add `:<git commit>` ?

**Comment by spiddy** [comment]
I think your text is missing some part. From the title I understand it doesn't push a tag you have created.

Currently (v0.8.0) it should push "latest", $working_branch and $tags list associated with the working commit-id.

Can you print your git tree here (you can remove the text of your commits), give an output of your captain command and mention what is missing.

You can use this oneliner for the git tree:

```
git log --all --graph --oneline --decorate
```

**Comment by dgil** [comment]
Hi @ludovicc! Did @spiddy solve your question? If not, can you please provide the information asked?

Thanks!

**Comment by spiddy** [comment]
Fixed on https://github.com/harbur/captain/pull/41

By default `commit` docker tags are not pushed to avoid bloating the registry but it can now be activated by using  the `--commit-tags` flag on `pull` & `push` subcommands.
