### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by dgil** [harbur/captain#38]
The test we have now only test a few simple cases. We should improve test coverage.

Also, we could add in the main page a badge with the coverage.

**Comment by spiddy** [comment]
Let's split this to two different scopes. Add CI integration to captain and improve test coverage.

The CI integration is now on #50 issue.

**Comment by dgil** [comment]
Great!

**Comment by spiddy** [comment]
Created an issue for adding coveralls integration #53
